name: Automated Release Process

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (x.y.z)"
        required: true
        type: string

env:
  REPO_NAME: marcelosalloum/stellar-disbursement-platform-backend

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate version format
        run: |
          if ! [[ ${{ inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in the format x.y.z (e.g., 1.0.0)"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Issue
        run: gh issue create --title "Release ${{ inputs.version }}" --body "Automating release process for ${{ inputs.version }}" --label "release" --assignee "${{ github.actor }}"

      - name: Create Branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          gh repo clone ${{ env.REPO_NAME }}
          cd stellar-disbursement-platform-backend
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b release/${{ inputs.version }} origin/develop
          git commit --allow-empty -m "chore: empty commit for release ${{ inputs.version }}"
          git push origin release/${{ inputs.version }}

          git checkout -b release/${{ inputs.version }}-dev release/${{ inputs.version }}
          git push origin release/${{ inputs.version }}-dev

      - name: Open Pull-Requests
        run: |
          gh pr create --repo ${{ env.REPO_NAME }} --base main --head release/${{ inputs.version }} --title "Release ${{ inputs.version }} to main" --body "Release ${{inputs.version}} to main"
          gh pr create --repo ${{ env.REPO_NAME }} --base develop --head release/${{ inputs.version }}-dev --title "Release ${{ inputs.version }}-dev to develop" --body "Release ${{inputs.version}} to develop"

      - name: Create Draft Release
        run: gh release create ${{ inputs.version }} --draft --notes "Initial draft for release ${{ inputs.version }}"
